[package]
name = "app"
version = "0.1.0-dev"
authors = ["Pieter Frenssen <pieter@frenssen.be>"]
edition = "2018"

[dependencies]
dotenv = "~0.15"
env_logger = "~0.7"
mockito = "^0.27.0"
regex = "^1.3.9"
